---
_hotel_id: SHE152
_portal_id: ''
latitude: 42.29693
longitude: -71.47967
name: Sheraton Framingham Hotel & Conference Center
email: ''
phone_number: "--"
address:
  street1: 1657 Worcester Rd
  street2: ''
  state: Massachusetts
  city: Framingham
  country: United States
  zip_code: '01701'
